# Generated by Django 5.2.3 on 2025-06-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('status', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Onboarding', 'Onboarding'), ('Active', 'Active'), ('Churned', 'Churned')])),
                ('address_street', models.CharField(max_length=100)),
                ('address_city', models.CharField(max_length=100)),
                ('address_state', models.CharField(max_length=100)),
                ('address_zip_code', models.CharField(max_length=100)),
            ],
        ),
    ]
